title: "My Blog"
description: "Breaking down web development, SEO, and full-stack concepts into easy-to-understand blogs. Learn, build, and grow with me!"  

baseurl: "/blogs"  
url: "https://tsdebug.github.io"  
theme: minima

# Custom permalink structure to remove date from URLs
permalink: "/:title/"

