title: "My Blog"
description: "Sharing how I set up Jekyll Blog."
baseurl: "/blogs"  
url: "https://tsdebug.github.io"  
theme: minima

# Custom permalink structure to remove date from URLs
permalink: "/:title/"

